name: develop

on:
  pull_request:
    types:
      - opened
  push:

jobs:
  develop:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Wabt
        run: |
          python script/build_wabt.py
          echo ${{ github.workspace }}/res/wabt/bin >> ${{ github.path }}
      - name: Test
        run: |
          python -m pip install --editable .
          python script/build_spec.py
          python script/build_wasi.py
          python test/example.py
          python test/main.py
          python test/spec.py
          python test/wasi.py
